//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTRIBUTE
    {
        public int ATTRIBUTE_ID { get; set; }
        public string ATTRIBUTE_NAME { get; set; }
        public string ATTRIBUTE_VALUE { get; set; }
        public int PRODUCT_ID { get; set; }
    }
}
