//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public int RECORD_ID { get; set; }
        public string CART_ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public int COUNT { get; set; }
        public System.DateTime TIME_CREATED { get; set; }
    }
}
